### ISSUE TITLE
Standalone CLI build fails with first-party plugin in config

### ISSUE THREAD

**Issue by youmustwearface** [tailwindlabs/tailwindcss#12119]
[Standalone CLI](https://tailwindcss.com/blog/standalone-cli) throws error since version 3.3.0 after adding first-party plugin in the config.

Tailwind CLI build 3.2.7 works without issue, it does not work in 3.3.x

Tested with **mac ARM 64-bit executable**.

config:
/** @type {import('tailwindcss').Config} */
export default {
  content: [],
  theme: {
    extend: {},
  },
  plugins: [
    require('@tailwindcss/forms'),
  ]
}

Error:
Rebuilding...
Error: Cannot find module '@tailwindcss/forms'
Require stack:
- /Users/xxx/tailwind.config.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function._resolveFilename (pkg/prelude/bootstrap.js:1955:46)
    at Function.resolve (node:internal/modules/cjs/helpers:108:19)
    at _resolve (/snapshot/tailwindcss/node_modules/jiti/dist/jiti.js:1:241066)
    at jiti (/snapshot/tailwindcss/node_modules/jiti/dist/jiti.js:1:243188)
    at /Users/xxx/tailwind.config.js:8:5
    at jiti (/snapshot/tailwindcss/node_modules/jiti/dist/jiti.js:1:245663)
    at loadConfig (/snapshot/tailwindcss/lib/lib/load-config.js:34:26)
    at Object.loadConfig (/snapshot/tailwindcss/lib/cli/build/plugin.js:133:49)
    at Object.getContext (/snapshot/tailwindcss/lib/cli/build/plugin.js:202:27) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/Users/xxx/tailwind.config.js' ]
}
