### PR TITLE
Expose `flattenColorPalette`

### LINKED ISSUE #15315: Trying to upgrade a plugin to v4
**What version of Tailwind CSS are you using?**

v4

**What build tool (or framework if it abstracts the build tool) are you using?**

"vite": "^6.0.1"

**What version of Node.js are you using?**

v20.18.0

**What browser are you using?**

N/A

**What operating system are you using?**

macOS

**Reproduction URL**

new vite project with tailwind and tailwindcss-motion
https://github.com/KevinGrajeda/plugin-v4

**Describe your issue**

I'm the developer of https://github.com/romboHQ/tailwindcss-motion and I'm trying to check the compatibility of the plugin with Tailwind v4 and when I run the project it throws me this error:

```
[plugin:@tailwindcss/vite:generate:serve] Package subpath './lib/util/flattenColorPalette' is not defined by "exports" in 
/Users/yokev/dev/rombo/example/upgrade-to-v4/node_modules/.pnpm/tailwindcss-motion@0.4.3-beta_tailwindcss@4.0.0-
beta.5/node_modules/tailwindcss/package.json
```

I'm using flattenColorPalette to add animations with the theme colors

https://github.com/romboHQ/tailwindcss-motion/blob/09ceaeca9654598bca430872f1c967eb066ca4a5/src/baseAnimations.js#L472-L473 

Is there a new approach for doing this? What can I do?

### PR DESCRIPTION
**Pull request by philipp-spiess**
Resolves #15315 

It looks like we implemented this in Core but forgot to expose it from the distributed package (the references are only used for testing plugins internally right now). This exposes `flattenColorPalette` under the old import path of `tailwindcss/lib/util/flattenColorPalette`.

## Test Plan

Added the following plugin to the Vite example and ensured it works as expected:

```ts
import flattenColorPalette from 'tailwindcss/lib/util/flattenColorPalette'
import plugin from 'tailwindcss/plugin'

export default plugin(({ matchUtilities, theme }) => {
  matchUtilities(
    {
      'hover-bg': (value) => {
        return {
          '&:hover': {
            backgroundColor: value,
          },
        }
      },
    },
    { values: flattenColorPalette(theme('colors')) },
  )
})
```

Screenshot 2024-12-06 at 11 47 44

### CODE REVIEW

File: packages/tailwindcss/package.json [hunk 1]
```diff
@@ -31,6 +31,10 @@
       "require": "./src/compat/colors.cts",
       "import": "./src/compat/colors.ts"
     },
+    "./lib/util/flattenColorPalette": {
+      "require": "./src/compat/flatten-color-palette.cts",
+      "import": "./src/compat/flatten-color-palette.ts"
+    },
```
Comment (thecrypticace) [inline packages/tailwindcss/package.json:37]: ngl kinda sad we have to export this one but makes sense.

File: packages/tailwindcss/src/compat/flatten-color-palette.cts [hunk 2]
```diff
@@ -0,0 +1,8 @@
+import flattenColorTheme from './flatten-color-palette.ts'
+
+// This file exists so that `default-theme.ts` can be written one time but be
```
Comment (thecrypticace) [inline packages/tailwindcss/src/compat/flatten-color-palette.cts:3]:
```suggestion
// This file exists so that `flatten-color-palette.ts` can be written one time but be
```

File: packages/tailwindcss/src/compat/flatten-color-palette.cts [hunk 3]
```diff
@@ -0,0 +1,8 @@
+import flattenColorTheme from './flatten-color-palette.ts'
```
Comment (thecrypticace) [inline packages/tailwindcss/src/compat/flatten-color-palette.cts:1]:
```suggestion
import flattenColorPalette from './flatten-color-palette.ts'
```

File: packages/tailwindcss/src/compat/flatten-color-palette.cts [hunk 4]
```diff
@@ -0,0 +1,8 @@
...
+
+// This file exists so that `default-theme.ts` can be written one time but be
+// compatible with both CJS and ESM. Without it we get a `.default` export when
+// using `require` in CJS.
+
+// @ts-ignore
+export = flattenColorTheme
```
Comment (thecrypticace) [inline packages/tailwindcss/src/compat/flatten-color-palette.cts:8]:
```suggestion
export = flattenColorPalette
```

File: packages/tailwindcss/package.json [hunk 5]
```diff
@@ -91,6 +95,10 @@
         "require": "./dist/colors.js",
         "import": "./dist/colors.mjs"
       },
+      "./lib/util/flattenColorPalette": {
+        "require": "./dist/flattenColorPalette.js",
+        "import": "./dist/flattenColorPalette.mjs"
```
Comment (thecrypticace) [inline packages/tailwindcss/package.json:100]: Can we name this with dashes please?

File: packages/tailwindcss/tsup.config.ts [hunk 6]
```diff
@@ -10,6 +10,7 @@ export default defineConfig([
       plugin: 'src/plugin.ts',
       colors: 'src/compat/colors.ts',
       'default-theme': 'src/compat/default-theme.ts',
+      flattenColorPalette: 'src/compat/flatten-color-palette.ts',
```
Comment (thecrypticace) [inline packages/tailwindcss/tsup.config.ts:13]:
```suggestion
      'flatten-color-palette': 'src/compat/flatten-color-palette.ts',
```

**Review by thecrypticace — CHANGES_REQUESTED** [review]
Left some notes about stuff but generally looks good

File: CHANGELOG.md [hunk 7]
```diff
@@ -7,14 +7,19 @@ and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0
...
 ## [Unreleased]
 
-- Nothing yet!
+### Added
+
+- Add support for `tailwindcss/lib/util/flattenColorPalette` exports ([#15318](https://github.com/tailwindlabs/tailwindcss/pull/15318))
+
+### Fixed
+
+- Fix dependency related warnings when using `@tailwindcss/postcss` on Windows ([#15321](https://github.com/tailwindlabs/tailwindcss/pull/15321))
```
Comment (RobinMalfait) [inline CHANGELOG.md:16]: Was a bit confused by this one, but makes sense!

**Review by RobinMalfait — APPROVED** [review]

File: CHANGELOG.md (hunk 7 above)
Comment (philipp-spiess) [reply CHANGELOG.md:16]: lol yeah my bad when I merged the other one 😕

**Comment by kadirmetin** [comment]
In my current project, after upgrading my Tailwind version from v3 to v4, I'm getting “TypeError: flattenColorPalette is not a function” error. I started to think that this feature was removed. Am I right?

> Error evaluating Node.js code
TypeError: flattenColorPalette is not a function
    [at addVariablesForColors (C:/Users/Kadir/Documents/Projects/locatr-monorepo/apps/web/tailwind.config.ts:133:21)]
    [at Ir (C:\Users\Kadir\Documents\Projects\locatr-monorepo\node_modules\tailwindcss\dist\lib.js:25:2050)]
    [at zr (C:\Users\Kadir\Documents\Projects\locatr-monorepo\node_modules\tailwindcss\dist\lib.js:25:1072)]
    [at async Lr (C:\Users\Kadir\Documents\Projects\locatr-monorepo\node_modules\tailwindcss\dist\lib.js:33:90)]
    [at async Mr (C:\Users\Kadir\Documents\Projects\locatr-monorepo\node_modules\tailwindcss\dist\lib.js:33:977)]
    [at async ot (C:\Users\Kadir\Documents\Projects\locatr-monorepo\node_modules\@tailwindcss\node\dist\index.js:10:3272)]
    [at async p (C:\Users\Kadir\Documents\Projects\locatr-monorepo\node_modules\@tailwindcss\postcss\dist\index.js:8:3242)]
    [at async Object.Once (C:\Users\Kadir\Documents\Projects\locatr-monorepo\node_modules\@tailwindcss\postcss\dist\index.js:8:3422)]
    [at async LazyResult.runAsync (turbopack:///[project]/node_modules/postcss/lib/lazy-result.js:293:11)]
    [at async transform (turbopack:///[project]/apps/web/postcss.config.mjs/transform.ts:80:34)]
    [at async run (turbopack:///[turbopack-node]/ipc/evaluate.ts:92:23)]


 ○ Compiling /_error ...
